name: Databricks Asset Bundle CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DATABRICKS_CLI_VERSION: "0.262.0"

jobs:
  # Validate and test the bundle
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Print Databricks CLI version
        run: |
          databricks -v
      
      - name: Configure Databricks CLI
        run: |
          echo "${{ secrets.DATABRICKS_CONFIG_DEV }}" > ~/.databrickscfg
        env:
          DATABRICKS_CONFIG_DEV: ${{ secrets.DATABRICKS_CONFIG_DEV }}

      - name: Validate bundle configuration
        run: |
          databricks bundle validate --target dev
          databricks bundle validate --target prod
        env:
          BUNDLE_VAR_bundle_uuid: "${{ secrets.BUNDLE_UUID }}"
          BUNDLE_VAR_catalog_name: "${{ secrets.CATALOG_NAME }}"
          BUNDLE_VAR_dev_user_email: "${{ secrets.DEV_USER_EMAIL }}"
          BUNDLE_VAR_prod_user_email: "${{ secrets.PROD_USER_EMAIL }}"
          BUNDLE_VAR_workspace_host: "${{ secrets.WORKSPACE_HOST }}"

  # Deploy to development environment
  deploy-prod:
    needs: validate
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Print Databricks CLI version
        run: |
          databricks -v

      - name: Configure Databricks CLI
        run: |
          echo "${{ secrets.DATABRICKS_CONFIG_DEV }}" > ~/.databrickscfg
        env:
          DATABRICKS_CONFIG_DEV: ${{ secrets.DATABRICKS_CONFIG_DEV }}

      - name: Deploy to development
        run: |
          databricks bundle deploy --target prod
        env:
          env:
          BUNDLE_VAR_bundle_uuid: "${{ secrets.BUNDLE_UUID }}"
          BUNDLE_VAR_catalog_name: "${{ secrets.CATALOG_NAME }}"
          BUNDLE_VAR_dev_user_email: "${{ secrets.DEV_USER_EMAIL }}"
          BUNDLE_VAR_prod_user_email: "${{ secrets.PROD_USER_EMAIL }}"
          BUNDLE_VAR_workspace_host: "${{ secrets.WORKSPACE_HOST }}"
